module.exports = {
  wrapper: {
    position: 'relative',
    height: ['200px', '200px', '200px'],
    overflow: 'hidden',
    top: '0',
  },
  topBar: {
    width: '100vw',
    height: '50px',
    backgroundColor: 'brandBar',
    backdropFilter: 'blur(0px)',
    position: 'absolute',
    top: '0',
    left: '0',
    opacity: '0.9',
    '& > a': {
      color: 'white !important',
      fontWeight: 200,
    },

  },
  secondRow: {
    position: 'absolute',
    top: '50px',
    width: '100%',
  },
  triangleTopright: {
    width: '0',
    height: '0',
    borderTopWidth: '50px',
    borderTopColor: 'brandBar',
    borderTopStyle: 'solid',
    borderLeft: '50px solid transparent',
    position: 'absolute',
    display: ['none', 'block', 'block'],
    right: '340px',
    opacity: '0.9',
    backdropFilter: 'blur(0px)',
  },
  rightOfTriangle: {
    width: '340px',
    height: '50px',
    backgroundColor: 'brandBar',
    position: 'absolute',
    display: ['none', 'block', 'block'],
    right: '0',
    opacity: '0.9',
    backdropFilter: 'blur(0px)',
  },
  ndLogo: {
    width: '180px',
    position: 'absolute',
    right: '70px',
    top: '30px',
    display: ['none', 'block', 'block'],
  },
  ndWordmark: {
    width: '301x',
    height: '50px',
    position: 'absolute',
    right: 'calc(50vw - 150px)',
    top: '0',
    display: ['block', 'none', 'none'],
  },

  // depreciated
  browseLink: {
    color: 'background',
    fontFamily: 'menu',
    fontSize: '18px',
    textDecoration: 'none',
    position: 'absolute',
    right: '410px',
    lineHeight: '50px',
    display: ['none', 'block', 'block'],
  },
  exhibitsLink: {
    color: 'background',
    fontFamily: 'menu',
    fontSize: '18px',
    textDecoration: 'none',
    position: 'absolute',
    right: '480px',
    lineHeight: '50px',
    display: ['none', 'block', 'block'],
  },
  loginWrapper: {
    position: 'absolute',
    right: ['auto', '320px', '320px'],
    left: ['0', 'auto', 'auto'],
  },
  heroWrapper: {
    height: '100px',
    margin: '0 auto 0',
    padding: '1rem',
    width: '100%',
    position: 'relative',
    maxWidth: '1540px',
  },
  marbleLogo: {
    height: '60px',
    top: ['90px', '15px', '15px'],
    left: ['calc(50vw - 120px)', '0', '0'],
    position: 'absolute',
  },
}
