import React from 'react'
import PropTypes from 'prop-types'
import { graphql, Link } from 'gatsby'
import { I18nextProvider } from 'react-i18next'
import i18next from '@ndlib/gatsby-theme-marble/src/i18n'
import Layout from '../components/layouts/HomePage'
import Seo from '@ndlib/gatsby-theme-marble/src/components/Internal/Seo'
import Column from 'components/Shared/Column'
import MultiColumn from 'components/Shared/MultiColumn'

const Home = ({ data, location }) => {
  return (
    <Layout
      location={location}
    >
      <Seo
        data={data}
        location={location}
      />
      <I18nextProvider i18n={i18next}>
        <section>
          <MultiColumn columns='2'>
            <Column>
              <p>
            The materials featured on this website are from the University of Notre Dame&apos;s Harley L. McDevitt Inquisition Collection. The collection consists of several hundred items, from printed volumes to unique manuscripts and images, all bearing some relationship to the general theme of &quot;inquisition.&quot; For the most part the documents were produced by the Spanish inquisition or its critics, though several pieces also relate to other regions. Thanks to the generosity of Harley L. McDevitt (ND &lsquo;29), Notre Dame was able to purchase the collection as a whole in 1997. Its contents comprise of one of the world&apos;s most important and distinctive private collections for inquisition studies.
              </p>
            </Column>
            <Column>
              <Link to='/item/MSHLAT0090_EAD'>Browse the Collection</Link>
            </Column>
          </MultiColumn>
          <MultiColumn columns='3'>
            <Column colSpan='1'>
              <Link to='/item/MSHLAT0090_EAD'>Essays</Link>
            </Column>
            <Column colSpan='2'>
              <p>
              This website is intended as a resource for students and researchers interested in histories of inquisitions worldwide. Though primarily focused on the Spanish inquisitions of the fifteenth to nineteenth centuries, attention is also paid to medieval inquisitions as well as to Portuguese, Roman and various New World inquisitions that existed from the sixteenth century onwards.
              </p>
              <p>
              Thematic introductory essays present various types of documents generated by and around these religious tribunals with references given for further reading. Examples of selected documents discussed in the essays are also provided to give viewers a virtual "hands-on" experience of examining such materials in their original format. Overall the goal is to stimulate and facilitate further exploration of inquisition history by familiarizing new generations with its extremely rich yet challenging documentary legacy.
              </p>
            </Column>
          </MultiColumn>
        </section>
        <section>
          <h2>Resources</h2>
          <p>The bibliographic descriptions and essays found on this site were prepared by Robin Vose, Associate Professor, Department of History at St. Thomas University, Fredericton, New Brunswick, Canada.</p>
          <Link to='/about'>About the Collection and this Digital Project</Link>
          <h3>Additional Resources about the Inquisition</h3>
          <ul>
            <li><Link to='/about'>A Brief History of the Inquisitions</Link></li>
            <li><Link to='/about'>A Timeline of the Inquisitions</Link></li>
            <li><Link to='/about'>Inquisitors-General of the Spanish Inquisition</Link></li>
          </ul>
          <h3>External Resources</h3>
          <ul>
            <li><Link to='/about'>Visiting the Collection and Contact Information</Link></li>
            <li><Link to='/about'>Access to Materials</Link></li>
            <li><Link to='/about'>Hours, Location & Contact Information</Link></li>
          </ul>
        </section>
      </I18nextProvider>
    </Layout>
  )
}

Home.propTypes = {
  data: PropTypes.object.isRequired,
  location: PropTypes.object.isRequired,
}
export default Home

export const query = graphql`
  query {
    site {
      siteMetadata {
        title
        description
        author
      }
    }
  }
`
