module.exports = {
  wrapper: {
    borderTop: '5px solid #D39F10',
    position: 'relative',
    height: ['290px', '380px', '380px'],
    overflow: 'hidden',
    background: 'white',
  },
  topBar: {
    width: '100vw',
    height: '50px',
    backgroundColor: 'brandBar',
    backdropFilter: 'blur(0px)',
    position: 'absolute',
    top: '0',
    left: '0',
    opacity: '0.9',
    '& > a': {
      color: 'white !important',
      fontWeight: 200,
    },

  },
  exhibitsLink: {
    color: 'background',
    fontFamily: 'menu',
    fontSize: '18px',
    textDecoration: 'none',
    position: 'absolute',
    right: '400px',
    lineHeight: '50px',
    display: ['none', 'block', 'block'],
  },
  secondRow: {
    position: 'absolute',
    top: '50px',
    width: '100%',
  },
  triangleTopright: {
    width: '0',
    height: '0',
    borderTopWidth: '50px',
    borderTopColor: 'brandBar',
    borderTopStyle: 'solid',
    borderLeft: '50px solid transparent',
    position: 'absolute',
    display: ['none', 'block', 'block'],
    right: '270px',
    opacity: '0.9',
    backdropFilter: 'blur(0px)',
  },
  rightOfTriangle: {
    width: '270px',
    height: '50px',
    backgroundColor: 'brandBar',
    position: 'absolute',
    display: ['none', 'block', 'block'],
    right: '0',
    opacity: '0.9',
    backdropFilter: 'blur(0px)',
  },
  ndLogo: {
    width: '180px',
    position: 'absolute',
    right: '70px',
    top: '30px',
    display: ['none', 'block', 'block'],
  },
  ndWordmark: {
    width: '301x',
    height: '50px',
    position: 'absolute',
    right: 'calc(50vw - 150px)',
    top: '0',
    display: ['block', 'none', 'none'],
  },
}
