module.exports = {
  wrapper: {
    borderTop: '5px solid #D39F10',
    position: 'relative',
    height: ['290px', '380px', '380px'],
    overflow: 'hidden',
    top: '15px',
  },
  topBar: {
    width: '100vw',
    height: '50px',
    backgroundColor: '#0C2340dd',
    backdropFilter: 'blur(0px)',
    position: 'absolute',
    top: '0',
    left: '0',
  },
  exhibitsLink: {
    color: 'background',
    fontFamily: 'menu',
    fontSize: '18px',
    textDecoration: 'none',
    position: 'absolute',
    right: '400px',
    lineHeight: '50px',
    display: ['none', 'block', 'block'],
  },
  loginWrapper: {
    position: 'absolute',
    right: ['auto', '320px', '320px'],
    left: ['0', 'auto', 'auto'],
  },
  secondRow: {
    position: 'absolute',
    top: '50px',
    width: '100%',
  },
  triangleTopright: {
    width: '0',
    height: '0',
    borderTop: '50px solid #0C2340dd',
    borderLeft: '50px solid transparent',
    position: 'absolute',
    display: ['none', 'block', 'block'],
    right: '270px',
    backdropFilter: 'blur(0px)',
  },
  rightOfTriangle: {
    width: '270px',
    height: '50px',
    backgroundColor: '#0C2340dd',
    position: 'absolute',
    display: ['none', 'block', 'block'],
    right: '0',
    backdropFilter: 'blur(0px)',
  },
  ndLogo: {
    width: '180px',
    position: 'absolute',
    right: '70px',
    top: '30px',
    display: ['none', 'block', 'block'],
  },
  ndWordmark: {
    width: '301x',
    height: '50px',
    position: 'absolute',
    right: 'calc(50vw - 150px)',
    top: '0',
    display: ['block', 'none', 'none'],
  },
}
